/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function new_url(a: number, b: number, c: number): void;
export function parse_url(a: number, b: number, c: number): void;
export function parse(a: number, b: number): void;
export function get_host(a: number, b: number, c: number): void;
export function get_host_url(a: number, b: number): void;
export function get_port(a: number, b: number, c: number): void;
export function get_port_url(a: number, b: number): void;
export function get_domain(a: number, b: number, c: number): void;
export function get_domain_url(a: number, b: number): void;
export function get_scheme(a: number, b: number, c: number): void;
export function get_scheme_url(a: number, b: number): void;
export function get_origin(a: number, b: number, c: number): void;
export function get_origin_url(a: number, b: number): void;
export function get_fragment(a: number, b: number, c: number): void;
export function get_fragment_url(a: number, b: number): void;
export function join_url(a: number, b: number, c: number, d: number, e: number): void;
export function join(a: number, b: number, c: number, d: number): void;
export function make_relative(a: number, b: number, c: number, d: number, e: number): void;
export function relative_partial(a: number, b: number, c: number, d: number): void;
export function relative(a: number, b: number, c: number): void;
export function get_password(a: number, b: number, c: number): void;
export function get_password_url(a: number, b: number): void;
export function get_pathname(a: number, b: number, c: number): void;
export function get_pathname_url(a: number, b: number): void;
export function get_path_segments(a: number, b: number, c: number): void;
export function get_path_segments_url(a: number, b: number): void;
export function get_query(a: number, b: number, c: number): void;
export function get_query_url(a: number, b: number): void;
export function get_username(a: number, b: number, c: number): void;
export function get_username_url(a: number, b: number): void;
export function get_query_pairs(a: number, b: number, c: number): void;
export function get_query_pairs_url(a: number, b: number): void;
export function set_host(a: number, b: number, c: number, d: number, e: number): void;
export function set_host_url(a: number, b: number, c: number, d: number): void;
export function set_port(a: number, b: number, c: number, d: number): void;
export function set_port_url(a: number, b: number, c: number): void;
export function set_scheme(a: number, b: number, c: number, d: number, e: number): void;
export function set_scheme_url(a: number, b: number, c: number, d: number): void;
export function set_fragment(a: number, b: number, c: number, d: number, e: number): void;
export function set_fragment_url(a: number, b: number, c: number, d: number): void;
export function set_password(a: number, b: number, c: number, d: number, e: number): void;
export function set_password_url(a: number, b: number, c: number, d: number): void;
export function set_pathname(a: number, b: number, c: number, d: number, e: number): void;
export function set_pathname_url(a: number, b: number, c: number, d: number): void;
export function set_path_segments(a: number, b: number, c: number, d: number, e: number): void;
export function set_path_segments_url(a: number, b: number, c: number, d: number): void;
export function set_query(a: number, b: number, c: number, d: number, e: number): void;
export function set_query_url(a: number, b: number, c: number, d: number): void;
export function set_username(a: number, b: number, c: number, d: number, e: number): void;
export function set_username_url(a: number, b: number, c: number, d: number): void;
export function set_query_pairs(a: number, b: number, c: number, d: number, e: number): void;
export function set_query_pairs_url(a: number, b: number, c: number, d: number): void;
export function get_hostname_url(a: number, b: number): void;
export function get_hostname(a: number, b: number, c: number): void;
export function set_hostname_url(a: number, b: number, c: number, d: number): void;
export function set_hostname(a: number, b: number, c: number, d: number, e: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
